kind: ConfigMap
apiVersion: v1
metadata:
  name: dynamic-plugins-rhdh
  namespace: demo-project
data:
  dynamic-plugins.yaml: |
    includes:
      - dynamic-plugins.default.yaml
    plugins:
      - package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-keycloak-backend-dynamic 
        # documentation: https://janus-idp.io/plugins/keycloak
        disabled: false
      - package: ./dynamic-plugins/dist/backstage-plugin-catalog-backend-module-github-dynamic
        # documentation: https://backstage.io/docs/integrations/github/discovery/
        disabled: false
      - package: ./dynamic-plugins/dist/roadiehq-backstage-plugin-argo-cd-backend-dynamic
        # documentation: https://docs.redhat.com/en/documentation/red_hat_developer_hub/0.1/html/argocd_plugin_for_backstage/argocd-plugin-for-backstage#installation
        # documentation: https://docs.redhat.com/en/documentation/red_hat_developer_hub/1.2/html/configuring_plugins_in_red_hat_developer_hub/rhdh-installing-dynamic-plugins#enabling-argo-cd-plugin
        disabled: false
      - package: ./dynamic-plugins/dist/roadiehq-scaffolder-backend-argocd-dynamic
        disabled: false
      - package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-tekton
        # documentation: https://docs.redhat.com/en/documentation/red_hat_plug-ins_for_backstage/1.0/html-single/tekton_plugin_for_backstage/index#setting-tekton-plugin
        disabled: false
      - package: ./dynamic-plugins/dist/backstage-plugin-kubernetes-backend-dynamic
        # documentation: https://backstage.io/docs/features/kubernetes/configuration/#config
        disabled: false
      - package: ./dynamic-plugins/dist/backstage-plugin-kubernetes
        disabled: false
      - package: ./dynamic-plugins/dist/backstage-plugin-jenkins-backend-dynamic
        # documentation: https://www.npmjs.com/package/@backstage-community/plugin-jenkins-backend
        disabled: false
      - package: ./dynamic-plugins/dist/backstage-plugin-jenkins
        disabled: false
      - package: ./dynamic-plugins/dist/backstage-community-plugin-3scale-backend-dynamic
        disabled: false
      - package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-topology
        # documentation: https://www.npmjs.com/package/@janus-idp/backstage-plugin-topology
        disabled: false
      - package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-rbac
        # documentation: https://docs.redhat.com/en/documentation/red_hat_developer_hub/1.3/html/authorization/con-rbac-overview_title-authorization
        disabled: false
      - package: 'https://developer-hub-plugins.s3.eu-west-3.amazonaws.com/ansible-self-service-plugin/internal-backstage-plugin-ansible-self-service-dynamic-0.1.0.tgz' 
        disabled: false
        integrity: 'sha512-fA+rAkTlrAt7nDdv88OB32UwIXKZjeu+x+P4gHDQONFNgnG/RU2mUdSGvjOeiyjKukyNj5zpcVNOnHYkmcTXpA==' #ansible-self-service-frontend-hash
      # - package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-aap-backend-dynamic
      #   # documentation: https://www.npmjs.com/package/@janus-idp/backstage-plugin-aap-backend-dynamic
      #   disabled: false
      #- package: 'http://plugin-registry:8080/internal-backstage-plugin-simple-chat-backend-dynamic-0.1.0.tgz'
      #  disabled: false
      #  integrity: 'sha512-sM9KFoRxPHVbpJ7+wur0bNSiNjLH/Q5oqfy+6Paz3xqVgQ05o3pu/+f0aFiUzNsUyyqLzqISikAf7yKM1I/iSw==' #backend-hash
      #- package: 'http://plugin-registry:8080/internal-backstage-plugin-simple-chat-dynamic-0.1.0.tgz' 
      #  disabled: false
      #  integrity: 'sha512-FnroSutG25FNnBey2o4QZh8t4VvCOu6P3P1NnLHEu41y3YMZbfqrN8QURqd5HDXTDgTFkBMNDmjFoTjv1flh7g==' #frontend-hash
      #- package: 'http://plugin-registry:8080/internal-backstage-plugin-keycloak-backend-dynamic-0.1.0.tgz' 
      #  disabled: false
      #  integrity: 'sha512-hQA0q7wqOFFLMAvv86FNpC/Bbxyoqo0tUJ7jX/zslbZlS+ahNq7sxzSbLaUeLPVRyFj1R8EcMDpEmNMJvo0DNg==' #keycloak-hash
      #- package: 'http://plugin-registry:8080/internal-backstage-plugin-scaffolder-backend-module-custom-action-argocd-create-resources-dynamic-0.1.0.tgz' 
      #  disabled: false
      #  integrity: 'sha512-q5NZVJAPJX3QAuIp3Bj1EXgf8srYpLCsZvJCJrLDa9UU87V9kCAPRQLx+H7SzmSpzRJwtqS37pZTseiG2b385Q==' #custom-action-argo-create-resources-hash
      #- package: '@roadiehq/backstage-plugin-argo-cd-backend@2.14.7'
      #  disabled: false
      #  integrity: 'sha512-4kyTcWjvOLJKE+xbrcmTmMKbAXZio1k2wddf7g367CC95DoW36HQvLCbRNr65tyhHEmml0rakeF40jEee5/uPA=='
      #if-minio-techdocs-disabled - package: ./dynamic-plugins/dist/backstage-plugin-techdocs-backend-dynamic
        #if-minio-techdocs-disabled # documentation: https://backstage.io/docs/features/techdocs/
        #if-minio-techdocs-disabled # documentation: https://backstage.io/docs/features/techdocs/configuration/
        #if-minio-techdocs-disabled # doc discovery: https://backstage.io/docs/integrations/aws-s3/discovery/
        #if-minio-techdocs-disabled # documentation: https://backstage.io/docs/features/techdocs/how-to-guides/
        #if-minio-techdocs-disabled # iframes in techdocs: https://backstage.io/docs/features/techdocs/how-to-guides/#how-to-add-the-documentation-setup-to-your-software-templates
        #if-minio-techdocs-disabled disabled: false
        #if-minio-techdocs-disabled pluginConfig: {}
      #if-aws-techdocs-disabled - package: ./dynamic-plugins/dist/backstage-plugin-techdocs-backend-dynamic
        #if-aws-techdocs-disabled # documentation: https://backstage.io/docs/features/techdocs/
        #if-aws-techdocs-disabled # documentation: https://backstage.io/docs/features/techdocs/configuration/
        #if-aws-techdocs-disabled # doc discovery: https://backstage.io/docs/integrations/aws-s3/discovery/
        #if-aws-techdocs-disabled # documentation: https://backstage.io/docs/features/techdocs/how-to-guides/
        #if-aws-techdocs-disabled # iframes in techdocs: https://backstage.io/docs/features/techdocs/how-to-guides/#how-to-add-the-documentation-setup-to-your-software-templates
        #if-aws-techdocs-disabled disabled: false
        #if-aws-techdocs-disabled pluginConfig: {}
      # - package: ./dynamic-plugins/dist/backstage-plugin-catalog-backend-module-github-org-dynamic # TODO enable when you want to sync...
      #                                                                                              # TODO ...users and groups from GitHub
      #   # documentation: https://docs.redhat.com/en/documentation/red_hat_developer_hub/1.3/html/authentication/assembly-auth-provider-github#provisioning-users-from-github-to-the-software-catalog
      #   disabled: false
      #   pluginConfig: {}
