apiVersion: rhdh.redhat.com/v1alpha1
kind: Backstage
metadata:
  name: developer-hub
  namespace: demo-project
spec:
  application:
    dynamicPluginsConfigMapName: dynamic-plugins-rhdh # added
    appConfig:
      mountPath: /opt/app-root/src
      configMaps:
        - name: app-config-rhdh
    extraFiles:
      mountPath: /opt/app-root/src
    extraEnvs:
      envs:
        # Disabling TLS verification
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: '0'
      secrets:
        - name: rhdh-secrets # added
        - name: rhdh-secrets-github-integration
        #if-aws-techdocs-disabled - name: rhdh-secrets-aws-s3-techdocs
        - name: rhdh-secrets-keycloak-rhdh-client
    replicas: 1
    route:
      enabled: true
  database:
    enableLocalDb: true
