kind: ConfigMap
apiVersion: v1
metadata:
  name: app-config-rhdh
  namespace: demo-project
data:
  app-config-rhdh.yaml: |
    signInPage: github   
    #signInPage: guest
    app:
      title: My Red Hat Developer Hub Instance
      baseUrl: https://backstage-developer-hub-demo-project.${basedomain} # be aware: project 'demo-project' is part of the url. Change it if you use another project
    backend:
      auth:
        keys:
          - secret: ${BACKEND_SECRET}
      baseUrl: https://backstage-developer-hub-demo-project.${basedomain} # be aware: project 'demo-project' is part of the url. Change it if you use another project
      cors:
        origin: https://backstage-developer-hub-demo-project.${basedomain} # be aware: project 'demo-project' is part of the url. Change it if you use another project
    integrations:
      github:
        - host: github.com
          apps:
            - appId: ${RHDH_GITHUB_APP_ID}
              clientId: ${RHDH_GITHUB_APP_CLIENT_ID}
              clientSecret: ${RHDH_GITHUB_APP_CLIENT_SECRET}
              webhookUrl: none
              webhookSecret: none
              privateKey: ${RHDH_GITHUB_APP_PRIVATE_KEY}
    catalog:
      processingInterval: { minutes: 1 }
      lifecycles:
        - production
        - staging
      rules:
        - allow: [Location, Component, API, Resource, System, Domain, Group, User, Template]
      locations:
        # a first location: a software template for a basic Quarkus project
        - type: url
          target: https://github.com/maarten-vandeperre/developer-hub-documentation/blob/main/configurations/software-templates/default-quarkus/template.yaml
          rules:
            - allow: [Template]
      providers:
        github:
          # the provider ID can be any camelCase string
          providerId:
            organization: 'maarten-dev-hub-training-organization' # string
            catalogPath: '/catalog-info.yaml' # string
            filters:
              branch: 'master' # string
              repository: '.*' # Regex
            schedule: # optional; same options as in TaskScheduleDefinition
              # supports cron, ISO duration, "human duration" as used in code
              frequency: { minutes: 1 }
              # supports ISO duration, "human duration" as used in code
              timeout: { minutes: 1 }
              initialDelay: { seconds: 15 }
        githubOrg:
          # the provider ID can be any camelCase string
          id: githubborg-maarten-dev-hub-training-organization
          orgs: [ 'maarten-dev-hub-training-organization' ]
          githubUrl: https://github.com # 'https://' is required!
          schedule: # optional; same options as in TaskScheduleDefinition
            # supports cron, ISO duration, "human duration" as used in code
            frequency: { minutes: 1 }
            # supports ISO duration, "human duration" as used in code
            timeout: { minutes: 1 }
            initialDelay: { seconds: 15 }
    auth:
      environment: development
      session:
        secret: ${BACKEND_SECRET}
      providers:
        github:
          development:
            clientId: ${RHDH_GITHUB_APP_CLIENT_ID}
            clientSecret: ${RHDH_GITHUB_APP_CLIENT_SECRET}
        # allow guest authentication for now
        guest:
          dangerouslyAllowOutsideDevelopment: true
