#install namespace
apiVersion: v1
kind: Namespace
metadata:
  name: rhdh-operator
---

#install demo project namespace
apiVersion: v1
kind: Namespace
metadata:
  name: demo-project
---

#install operator group
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: developer-hub-operator-group
  namespace: rhdh-operator
---

#install operator group of demo-project namespace
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: demo-project-operator-group
  namespace: demo-project
spec:
  targetNamespaces:
    - demo-project
---

#install developer hub operator
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: developer-hub-operator-subscription
  namespace: openshift-operators
spec:
  channel: fast
  installPlanApproval: Automatic
  name: rhdh
  source: redhat-operators
  sourceNamespace: openshift-marketplace