apiVersion: v1
kind: Secret
metadata:
  name: ecorp-admin-secret
  namespace: demo-project
type: Opaque
stringData:
  admin_password: averysecurepassword
---
apiVersion: capabilities.3scale.net/v1alpha1
kind: Tenant
metadata:
  name: demo-organization-maarten
  namespace: demo-project
spec:
  masterCredentialsRef:
    name: system-seed
    namespace: demo-project
  passwordCredentialsRef:
    name: ecorp-admin-secret
    namespace: demo-project
  tenantSecretRef:
    name: tenant-secret
    namespace: demo-project
  email: maarten.vandeperre@redhat.com
  organizationName: Demo Organization maarten 6
  systemMasterUrl: 'https://master.apps.cluster-m6l5s.m6l5s.sandbox2334.opentlc.com'
  username: admin
# admin url becomes demo-organization-maarten-5-admin.apps.cluster-m6l5s.m6l5s.sandbox2334.opentlc.com/p/admin/dashboard