apiVersion: apps.3scale.net/v1alpha1
kind: APIManager
metadata:
  name: apimanager-demo-project
  namespace: demo-project
spec:
  monitoring:
    enablePrometheusRules: false
    enabled: false  # Disable Grafana integration
  system:
#    fileStorage:
#      persistentVolumeClaim:
#        storageClassName: manual
    fileStorage:
      simpleStorageService:
        configurationSecretRef:
          name: s3-storage-credentials
        configurationConfigMapRef:
          name: s3-storage-config
        bucket: 3scale
        awsRegion: eu-west-3
  wildcardDomain: apps.cluster-gc2np.gc2np.sandbox1466.opentlc.com
