apiVersion: v1
kind: Namespace
metadata:
  name: demo-project
---
apiVersion: v1
kind: Namespace
metadata:
  name: rhdh-operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-gitops-operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager-operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: aap
---
apiVersion: v1
kind: Namespace
metadata:
  name: redhat-ods-operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-distributed-tracing
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-tempo-operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-opentelemetry-operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: tracing-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: maarten-test-1
---
apiVersion: v1
kind: Namespace
metadata:
  name: maarten-test-2